// MA-SEC-002 P7 — versioned, auto-appended, non-optional

export const DISCLAIMERS: Record<string, string> = {
  '1.0.0': `

---
IMPORTANT DISCLAIMER: This letter was generated by MyAdvocate as informational guidance only.
It does not constitute legal or medical advice. MyAdvocate is not a law firm or medical provider.
The information provided may not apply to your specific situation. Please consult a qualified
attorney or healthcare professional before taking action. MyAdvocate makes no guarantees about
the outcome of any appeal or dispute process.
`,
}

export const CURRENT_DISCLAIMER_VERSION = '1.0.0'

export function appendDisclaimer(content: string, version = CURRENT_DISCLAIMER_VERSION): string {
  const disclaimer = DISCLAIMERS[version]
  if (!disclaimer) throw new Error(`Unknown disclaimer version: ${version}`)
  return content + disclaimer
}
