// MA-EEAT-001 §5.1 — Trust infrastructure page: Medical Disclaimer
// MA-SEC-002 P7 — Versioned disclaimer, attorney-reviewed scope statement
// STATUS: ATTORNEY REVIEW REQUIRED before publish
// Priority: Launch blocker

export const metadata = {
  title: 'Medical Disclaimer — MyAdvocate',
  description:
    'MyAdvocate provides patient advocacy navigation information, not legal or medical advice. Read our full disclaimer and scope statement.',
}

export default function MedicalDisclaimerPage() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-12">

      <h1 className="text-3xl font-bold mb-2">Medical Disclaimer</h1>
      <p className="text-sm text-gray-500 mb-8">Last reviewed by the MyAdvocate Editorial Board</p>

      <div className="bg-yellow-50 border border-yellow-300 rounded-lg p-5 mb-10">
        <p className="font-semibold text-yellow-800 mb-2">Important — Please Read</p>
        <p className="text-yellow-800 text-sm">
          The information provided on MyAdvocate is for general patient navigation and
          advocacy purposes only. It does not constitute legal advice, medical advice,
          diagnosis, or treatment. Always consult a qualified healthcare provider for
          medical decisions and a licensed attorney for legal questions specific to
          your situation.
        </p>
      </div>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-3">What MyAdvocate Provides</h2>
        <p className="text-gray-700 mb-4">
          MyAdvocate provides information and tools to help patients:
        </p>
        <ul className="list-disc pl-6 text-gray-700 space-y-2">
          <li>Understand insurance denial codes and what they mean</li>
          <li>Learn about their general rights as patients under federal law</li>
          <li>Generate template letters for appeals, billing disputes, and records requests</li>
          <li>Navigate the processes available to challenge insurance and billing decisions</li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-3">What MyAdvocate Does Not Provide</h2>
        <ul className="list-disc pl-6 text-gray-700 space-y-2">
          <li>
            <strong>Legal advice:</strong> Nothing on MyAdvocate constitutes legal advice
            or creates an attorney-client relationship. For legal advice specific to your
            situation, consult a licensed attorney.
          </li>
          <li>
            <strong>Medical advice:</strong> Nothing on MyAdvocate constitutes medical
            advice, diagnosis, or treatment recommendation. For medical decisions,
            consult your healthcare provider.
          </li>
          <li>
            <strong>Outcome guarantees:</strong> MyAdvocate makes no representations or
            warranties about the outcome of any appeal, dispute, or records request.
            Results depend on individual circumstances, plan terms, applicable law,
            and many other factors outside our control.
          </li>
          <li>
            <strong>State-specific legal conclusions:</strong> Information about state
            patient rights is general in nature. Laws vary by state and individual situation.
            Consult an attorney for state-specific legal questions.
          </li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-3">Accuracy and Currency</h2>
        <p className="text-gray-700 mb-4">
          MyAdvocate makes reasonable efforts to keep content accurate and current.
          Healthcare policy, insurance regulations, and patient rights protections change
          over time. Information on this site may not reflect the most recent changes.
          Always verify important information with official government sources
          (CMS, your state insurance commissioner, HHS) or a qualified professional
          before taking action.
        </p>
        <p className="text-gray-700">
          If you believe any content is inaccurate, please contact us at{' '}
          <a href="mailto:admin@getmyadvocate.org" className="text-blue-600 underline">
            admin@getmyadvocate.org
          </a>.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-3">Template Letters</h2>
        <p className="text-gray-700">
          Template letters and scripts generated by MyAdvocate are starting points for
          patient advocacy — not finished legal documents. You are responsible for reviewing
          any letter before sending it, verifying that the information is accurate and
          applicable to your situation, and seeking professional advice if you have
          questions about its content or appropriateness.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="text-xl font-semibold mb-3">No Professional Relationship</h2>
        <p className="text-gray-700">
          Use of MyAdvocate does not create a professional relationship of any kind,
          including but not limited to an attorney-client relationship, doctor-patient
          relationship, or patient advocate relationship. MyAdvocate is an information
          platform, not a professional services firm.
        </p>
      </section>

      <p className="text-xs text-gray-400 mt-10 border-t pt-4">
        This disclaimer applies to all content and tools on MyAdvocate. It does not
        constitute legal advice and is subject to periodic review by counsel.
        Last reviewed by the MyAdvocate Editorial Board.
      </p>

    </main>
  )
}
