/**
 * MA-MEM-002 | TIMS TypeScript Type Definitions
 * Authority: MA-MEM-001 | Taxonomy: MA-TRJ-001
 * Generated from Supabase schema migrations 001–005
 *
 * Usage: import these types throughout the codebase wherever TIMS
 * data is created, read, or passed between functions.
 *
 * IMPORTANT: Enum values here MUST stay in sync with MA-TRJ-001.
 * Any taxonomy change requires updating both the SQL migration AND this file.
 */

// ── Enum Types ────────────────────────────────────────────────

export type WorkflowType =
  | 'denial_appeal'
  | 'bill_dispute'
  | 'denial_decode'
  | 'resource_route'
  | 'report_abuse';

export type OutputClass =
  | 'letter_generated'
  | 'explanation_only'
  | 'escalation_required'
  | 'insufficient_input'
  | 'error';

export type UserAction =
  | 'saved'
  | 'downloaded'
  | 'copied'
  | 'abandoned';

export type TierAtExecution =
  | 'free'
  | 'standard'
  | 'founding'
  | 'per_case';

export type CostBucket = 'low' | 'medium' | 'high';
export type DurationBucket = 'fast' | 'medium' | 'slow';
export type LetterLengthBucket = 'short' | 'medium' | 'long';

export type MemoryClass = 'strategy' | 'recovery' | 'optimization';

export type MemoryStatus =
  | 'draft'
  | 'eligible'
  | 'approved'
  | 'restricted'
  | 'retired';

export type YmylSensitivity = 'low' | 'medium' | 'high';

export type ComplianceReviewStatus =
  | 'pending'
  | 'approved'
  | 'flagged'
  | 'rejected';

export type RetrievalStrategy = 'metadata_match' | 'hybrid';

export type OutcomeType =
  | 'appeal_won'
  | 'appeal_pending'
  | 'appeal_lost'
  | 'dispute_resolved'
  | 'dispute_pending'
  | 'dispute_failed'
  | 'no_response'
  | 'user_reported_helpful'
  | 'user_reported_unhelpful';

export type OutcomeSource =
  | 'beehiiv_survey'
  | 'in_app_feedback'
  | 'attorney_referral_close'
  | 'user_self_report';

export type OutcomeConfidence = 'high' | 'medium' | 'low';

// Denial code families (MA-TRJ-001 §2)
export type DenialCodeFamily =
  | 'AUTH' | 'COV' | 'MED' | 'COORD' | 'DUP'
  | 'INFO' | 'PROC' | 'LIMIT' | 'EXCL' | 'APPEAL' | 'OTHER';

// Insurer categories (MA-TRJ-001 §3)
export type InsurerCategory =
  | 'BCBS_NATIONAL' | 'BCBS_REGIONAL' | 'AETNA' | 'CIGNA' | 'UNITED'
  | 'HUMANA' | 'CENTENE' | 'MOLINA' | 'KAISER'
  | 'REGIONAL_HMO' | 'REGIONAL_PPO' | 'MEDICAID_STATE'
  | 'MEDICARE_ADVANTAGE' | 'SELF_INSURED' | 'UNKNOWN';

// Procedure categories (MA-TRJ-001 §4)
export type ProcedureCategory =
  | 'IMAGING' | 'LAB' | 'SURGERY' | 'MENTAL_HEALTH' | 'PHYSICAL_THERAPY'
  | 'PHARMACY' | 'SPECIALIST' | 'PRIMARY_CARE' | 'EMERGENCY' | 'DME'
  | 'HOME_HEALTH' | 'PREVENTIVE' | 'REHAB' | 'TELEHEALTH' | 'OTHER';

// ── TrajectoryEvent ───────────────────────────────────────────

/**
 * Emitted by generateLetter() on every execution.
 * NO PII in any field. Written AFTER the four-layer privacy gate.
 */
export interface TrajectoryEvent {
  id: string; // UUID
  created_at: string; // ISO 8601 timestamp

  // Workflow context (bucketed / abstracted)
  workflow_type: WorkflowType;
  denial_code_family: DenialCodeFamily | null;
  insurer_category: InsurerCategory | null;
  state_code: string | null; // 2-letter, e.g. 'TX'. Null if not relevant.
  procedure_category: ProcedureCategory | null;

  // Execution context
  prompt_template_version: string;
  model_used: string; // e.g., 'claude-haiku-4-5-20251001', 'claude-sonnet-4-6'
  tools_invoked: string[];
  retrieval_sources_count: number | null;
  compliance_flags: string[];
  output_class: OutputClass;
  letter_length_bucket: LetterLengthBucket | null;

  // User signal
  user_action: UserAction | null;

  // Session (NOT linked to user_id — firewall enforced)
  session_id: string; // UUID

  // Cost / tier context
  tier_at_execution: TierAtExecution | null;
  api_cost_bucket: CostBucket | null;
  execution_duration_ms_bucket: DurationBucket | null;

  // Recovery context
  fallback_triggered: boolean;
  recovery_pattern_used: string | null;

  // Outcome linkage (null at write time)
  outcome_id: string | null; // FK to OutcomeRecord
}

/**
 * Payload emitted by generateLetter() — the write interface.
 * id and created_at are generated by the database.
 */
export type TrajectoryEventInsert = Omit<TrajectoryEvent, 'id' | 'created_at'>;

// ── MemoryTriggerConditions ───────────────────────────────────

/**
 * JSONB trigger conditions for memory retrieval matching.
 * All fields optional. More specificity = narrower match.
 * Retrieval uses containment: event context @> trigger_conditions.
 */
export interface MemoryTriggerConditions {
  workflow_type?: WorkflowType;
  denial_code_family?: DenialCodeFamily;
  insurer_category?: InsurerCategory;
  state_code?: string; // 2-letter state
  procedure_category?: ProcedureCategory;
}

// ── MemoryObject ──────────────────────────────────────────────

/**
 * A curated learning object generated from trajectory clusters.
 * Injected into future prompts via the Prompt Template Registry.
 * NO PII. No legal claims. Procedural only.
 */
export interface MemoryObject {
  id: string; // UUID
  created_at: string;
  updated_at: string;

  memory_class: MemoryClass;
  workflow_type: WorkflowType;
  trigger_conditions: MemoryTriggerConditions;

  /** Max 500 chars. No legal claims. No user data. Procedural only. */
  content: string;

  source_trajectory_ids: string[]; // UUID[]
  prompt_template_versions: string[];
  legal_source_citations: string[]; // Audit only — NOT injected into prompts

  memory_status: MemoryStatus;
  ymyl_sensitivity: YmylSensitivity;
  compliance_review_status: ComplianceReviewStatus;

  kate_reviewed: boolean;
  kate_reviewed_at: string | null;
  founder_reviewed_at: string | null;

  outcome_sample_size: number | null;
  /** 0.0–1.0. Thresholds: optimization >= 0.3, strategy/recovery >= 0.5 (OQ-02) */
  positive_outcome_rate: number | null;

  retrieval_count: number;
  retrieval_lift_score: number | null;
  retirement_reason: string | null;
  expires_at: string | null;
  law_change_flagged: boolean;
}

// ── PromptTemplateMemoryConfig ────────────────────────────────

/**
 * Memory configuration fields on each Prompt Template.
 * Extended from the existing prompt_templates table.
 */
export interface PromptTemplateMemoryConfig {
  memory_enabled: boolean;
  allowed_memory_classes: MemoryClass[];
  /** Hard cap: 1–5. Code-enforced in generateLetter(). */
  max_memories_injected: number;
  ymyl_sensitivity: YmylSensitivity;
  memory_retrieval_strategy: RetrievalStrategy;
  require_approved_status: boolean;
  /** PERMANENT HOSPITAL MODE FIREWALL. If true, memory injection is disabled regardless of memory_enabled. */
  hospital_mode_template: boolean;
}

// ── OutcomeRecord ─────────────────────────────────────────────

export interface OutcomeRecord {
  id: string; // UUID
  trajectory_event_id: string; // FK to TrajectoryEvent

  outcome_type: OutcomeType;
  reported_at: string;
  source: OutcomeSource;
  confidence: OutcomeConfidence;

  /** Only true for confidence >= medium AND non-pending outcome types */
  memory_promotion_eligible: boolean;
  signal_metadata: Record<string, unknown>; // No PII
}

// ── MemoryRetrievalLog ────────────────────────────────────────

export interface MemoryRetrievalLog {
  id: string; // UUID
  retrieved_at: string;

  trajectory_event_id: string; // FK to TrajectoryEvent

  memory_ids_retrieved: string[]; // All returned before cap
  memory_ids_injected: string[]; // Actually injected (after cap)

  retrieval_strategy_used: RetrievalStrategy;
  match_scores: number[]; // Parallel to memory_ids_retrieved

  user_action_post_retrieval: UserAction | null;
  memory_was_injected: boolean; // Generated column: memory_ids_injected.length > 0
}

// ── generateLetter() Integration Types ───────────────────────

/**
 * Context passed to the TIMS retrieval layer before inference.
 * Derived from the current execution context (scrubbed of PII).
 */
export interface TimsRetrievalContext {
  workflow_type: WorkflowType;
  denial_code_family?: DenialCodeFamily;
  insurer_category?: InsurerCategory;
  state_code?: string;
  procedure_category?: ProcedureCategory;
  prompt_template_id: string;
}

/**
 * Result of the TIMS retrieval query.
 * Injected into the prompt context up to max_memories_injected.
 */
export interface TimsRetrievalResult {
  memories_retrieved: MemoryObject[];
  memories_injected: MemoryObject[];
  retrieval_strategy: RetrievalStrategy;
  match_scores: number[];
}

/**
 * The full TIMS pre/post execution wrapper for generateLetter().
 *
 * Pre-execution:
 *   1. Check prompt_template.memory_enabled
 *   2. If hospital_mode_template = true → skip retrieval entirely
 *   3. Run retrieval query → get TimsRetrievalResult
 *   4. Inject memories into prompt context
 *
 * Post-execution:
 *   1. Emit TrajectoryEventInsert (scrubbed, after privacy gate)
 *   2. Write MemoryRetrievalLog entry
 */
export interface TimsExecutionWrapper {
  pre: {
    context: TimsRetrievalContext;
    config: PromptTemplateMemoryConfig;
    retrieval_result: TimsRetrievalResult | null; // null if memory_enabled = false
  };
  post: {
    trajectory_event: TrajectoryEventInsert;
    retrieval_log: Omit<MemoryRetrievalLog, 'id' | 'retrieved_at'> | null;
  };
}

// ── Memory Curator Output ─────────────────────────────────────

/**
 * Output of the Memory Curator n8n workflow Step 4.
 * Either a draft MemoryObject or a skip signal.
 */
export type MemoryCuratorOutput =
  | {
      skip: false;
      draft: {
        memory_class: MemoryClass;
        workflow_type: WorkflowType;
        trigger_conditions: MemoryTriggerConditions;
        content: string; // Max 500 chars. No legal claims.
        source_trajectory_ids: string[];
        prompt_template_versions: string[];
        ymyl_sensitivity: YmylSensitivity;
        outcome_sample_size: number;
        positive_outcome_rate: number;
      };
    }
  | {
      skip: true;
      reason: string; // Brief explanation for the skip
    };
